# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.sh 
      **/*.war
      **/*jar-with-dependencies.jar
    TargetFolder: '$(System.DefaultWorkingDirectory)/pipeline-artifacts/'
    flattenFolders: true

- task: AzureImageBuilderTask@1
  displayName: 'Azure VM Image Builder Task'
  inputs:
    managedIdentity: '/subscriptions/555e9625-1109-4ea1-becc-46f545846d55/resourcegroups/myVMSSResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myVMSSIdentity'
    imageSource: 'marketplace'
    packagePath: '$(System.DefaultWorkingDirectory)/pipeline-artifacts'
    inlineScript: |
      sudo mkdir /lib/buildArtifacts
      sudo cp  "/tmp/pipeline-artifacts.tar.gz" /lib/buildArtifacts/.
      cd /lib/buildArtifacts/.
      sudo tar -zxvf pipeline-artifacts.tar.gz
      sudo sh install.sh
    storageAccountName: 'vmssstorageaccount001'
    distributeType: 'sig'
    galleryImageId: '/subscriptions/555e9625-1109-4ea1-becc-46f545846d55/resourceGroups/myVMSSResourceGroup/providers/Microsoft.Compute/galleries/myVMSSGallery/images/MyImage/versions/0.0.$(Build.BuildId)'
    replicationRegions: 'westeurope'
    ibSubscription: '555e9625-1109-4ea1-becc-46f545846d55'
    ibAzureResourceGroup: 'myVMSSResourceGroup'
    ibLocation: 'westeurope'

