trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption(555e9625-1109-4ea1-becc-46f545846d55)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name myVMSSResourceGroup --location northeurope'
    failOnStandardError: true
